### ISSUE TITLE
Tooltip placement needs to be configurable

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/ax-input-control#21]
Currently the placement of the error tooltip is only determined by the type of input / select control it is attached to. In some cases this isn't sufficient and placement needs to be manually specified depending on other styling or content relevant requirements.

Example for a possible configuration:  `<input ax-input ax-input-tooltip-placement="top">`

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### Upgrade Information

The new directive attribute `ax-input-tooltip-placement` was added:
- If set, its string value _(left/right/bottom/top)_ is forwarded to the bootstrap tooltip component to determine tooltip placement on screen. Otherwise, the position is determined automatically depending on the type of form element and its position on screen (left/right for select boxes, top/bottom for other controls).
